### ISSUE TITLE
Добавить быстрое подключение

### ISSUE THREAD

**Issue by ademaro** [ArtMan-8/outline-prototype#1]
В консоле браузера написать `s=document.createElement('link');s.rel='stylesheet';s.href='https://rawcdn.githack.com/ArtMan-8/outline-prototype/07f7a9d439da3969ec343e1c2fdac38da94d6b4d/css/outline-prototype.css';document.body.appendChild(s);`

**Comment by ArtMan-8** [comment]
Интересный способ, добавил :+1:
