### ISSUE TITLE
Ломается вёрстка в некоторых кейсах

### ISSUE THREAD

**Issue by ademaro** [ArtMan-8/outline-prototype#2]
Вот конкретный кейс, ломает разметку, а не хотелось бы)
https://htmlacademy-htmlcss.github.io/809989-technomart-26/9/catalog.html

**Comment by ArtMan-8** [comment]
> Вот конкретный кейс, ломает разметку, а не хотелось бы)
> https://htmlacademy-htmlcss.github.io/809989-technomart-26/9/catalog.html

@ademaro да, есть такое дело (
Пока вижу это так:
- оставить текущий вариант css для базовой разметки, когда только накидывается макет, и нет псевдо элементов ::before ::after
- и сделать второй вариант css без подписей, когда макет уже свёрстан и добавляется стилизация

**Comment by ArtMan-8** [comment]
Сделал два варианта - с подписями и без
